### ISSUE TITLE
Identify INCLUDE statement

### ISSUE THREAD

**Issue by sbcgua** [sbcgua/abap_include_assembler#1]
There are case when `include xxx.` does not mean program include. E.g include of a structure (is it the only one?). Consequently current parser does not identify that. 

Options:
- Find an explicit way to get program includes via some FM (I don't know FMs like this)
- explicitely mark includes to process in the text e.g. `"!ASSEMBLE` - not very convenient but flexible
- after unsuccessful include load try to check if this is structure include -> then don't fail
- track appearance and context of `types` key word

Not sure what is better for the moment.

**Comment by sshlapak** [comment]
You can use FM GET_INCLUDETAB that scans program code looking for 'INCLUDE' and then skips lines where 'INCLUDE' is followed by  'STRUCTURE', 'TYPE',  'LIKE',  'METHODS'. 

Also take a look at  FM RS_GET_ALL_INCLUDES can be used that gets data from table D010INC.

**Comment by sbcgua** [comment]
Thanks for the comment ! RS_GET_ALL_INCLUDES look fine !
For time being decided to improve parsing and not using the FM. Because the FM can be executed on program level only (and that changes the architecture) and in particular can harden the integration abilities (another method to be implemented in the accessor interface).

Closed with bc07bf398d8f4a8e4902cfdbadbf3238a17850ca

**Comment by sbcgua** [comment]
P.S. OMG it finally parses ZUA_VAT_MIGRATE without a dump ... ;)
